/**
 * The panel's UI dictionaries — Simplified Chinese and English, mirrored.
 *
 * These are plain data, so they live in their own module rather than inside
 * the client bundle: `panel-decision.js` imports them to check that the two
 * languages stay key-for-key in sync, and importing the real dictionaries
 * replaces the string-scraping pass that used to read them out of client.js.
 *
 * The bundle (client.js) imports this file — the module loader resolves the
 * relative import — and passes both objects to `ctx.locale.register`, which
 * stays the single registration point.
 * @module dsh-connect-sensenova-token-plan/client-strings
 */

/** Simplified Chinese dictionary (the key-set source of truth). */
export const zh = {
  "entry.label": "积分面板",
  "panel.title": "积分面板",
  "panel.back": "返回会话",
  "panel.refresh": "刷新",
  "panel.updated": "更新于 {time}",
  "panel.loading": "加载中…",
  "panel.error": "读取失败：{error}",
  "panel.jwtMissing": "还没有配置控制台账号。",
  "panel.jwtExpired": "控制台令牌已失效，且无法用已保存的 refresh_token 续期。请重新登录一次。",
  "panel.configError": "插件配置有误：{error}",
  "panel.shapeDrift": "上游返回的结构可能有变：{detail}",
  "auth.title": "连接商汤控制台",
  "auth.username": "账号",
  "auth.password": "密码",
  "auth.show": "显示",
  "auth.hide": "隐藏",
  "auth.placeholderUser": "登录 platform.sensenova.cn 的账号",
  "auth.submit": "登录",
  "auth.submitting": "登录中…",
  "auth.working": "已保存并登录，正在读取额度…",
  "auth.forget": "清除已保存的账号",
  "auth.forgotten": "已清除账号（当前令牌仍可用）",
  "auth.saved": "账号已保存在 DSH 凭据中，不会写入插件目录",
  "auth.ephemeral": "注意：当前 Host 没有凭据服务，账号只保存在内存中，重启后需要重新登录。",
  "auth.badCredentials": "账号或密码不正确",
  "auth.locked": "账号已被锁定，请在商汤控制台用手机号验证或联系客服解锁。",
  "auth.retryAfter": "平台要求等待约 {minutes} 分钟后再试；等待期间面板不会自动重试，避免再次触发锁定。",
  "auth.rateLimited": "尝试过于频繁，请稍后再试。",
  "auth.verification": "需要额外验证（短信/图形验证码），自动化登录无法完成，请先在浏览器登录一次。",
  "auth.failed": "登录未完成：{reason}",
  "auth.empty": "请填写账号和密码",
  "auth.network": "无法连接本机 Host",
  "panel.empty": "暂无数据。",
  "section.pools": "积分池",
  "pool.window5h": "5 小时",
  "pool.window7d": "每周",
  "pool.used": "已用",
  "pool.remaining": "剩余",
  "pool.reset": "重置 {time}",
  "pool.grant": "返赠余额 {balance}",
  "pool.grantExpiry": "最近返赠到期 {time}（{balance} 分）",
  "pool.models": "模型",
  "pool.dedicated": "专属池",
  "pool.default": "通用池",
  "pool.callable": "可调用",
  "pool.locked": "需开通 +{count} 个",
  "pool.lockedTitle": "套餐覆盖但当前 Key 无权限",
  "pool.uncounted": "不计入积分池：{models}",
  "shape.api": "接口",
  "shape.missing": "缺少字段",
  "section.trend": "每模型消耗（近 {hours} 小时）",
  "trend.model": "模型",
  "trend.credits": "积分",
  "trend.none": "该区间内没有消耗记录。",
  "auth.selfRenew": "令牌自动续期中",
  "auth.needsLogin": "需要重新登录",
  "note": "数据来自商汤控制台 API（pool-usage / credit-usage-trend），Host 侧缓存 {cache} 秒；控制台令牌约 3 小时过期，由 Host 用 refresh_token 静默续期。"
};

/** English dictionary, mirroring every zh key. */
export const en = {
  "entry.label": "Credits",
  "panel.title": "Credits",
  "panel.back": "Back to conversation",
  "panel.refresh": "Refresh",
  "panel.updated": "Updated {time}",
  "panel.loading": "Loading…",
  "panel.error": "Could not read: {error}",
  "panel.jwtMissing": "No SenseNova console account is configured yet.",
  "panel.jwtExpired": "The console token is no longer valid and could not be renewed from the stored refresh_token. Sign in again.",
  "panel.configError": "The plugin is misconfigured: {error}",
  "panel.shapeDrift": "The upstream payload shape may have changed: {detail}",
  "auth.title": "Connect the SenseNova console",
  "auth.username": "Username",
  "auth.password": "Password",
  "auth.show": "Show",
  "auth.hide": "Hide",
  "auth.placeholderUser": "Your platform.sensenova.cn account",
  "auth.submit": "Sign in",
  "auth.submitting": "Signing in…",
  "auth.working": "Saved and signed in; reading quota…",
  "auth.forget": "Forget the saved account",
  "auth.forgotten": "Account cleared (the current token still works)",
  "auth.saved": "Stored in the DSH credentials, not in this plugin's folder",
  "auth.ephemeral": "Note: this Host has no credentials service, so the account lives in memory only and must be entered again after a restart.",
  "auth.badCredentials": "That username or password is not right",
  "auth.locked": "This account is locked. Verify by phone in the SenseNova console or contact support to unlock it.",
  "auth.retryAfter": "The platform asks to wait about {minutes} more minutes. The panel will not retry on its own during that window, so the lock is not extended.",
  "auth.rateLimited": "Too many attempts. Wait a moment and try again.",
  "auth.verification": "This sign-in needs an extra step (SMS or captcha) that automation cannot complete. Sign in once in a browser first.",
  "auth.failed": "Sign-in did not complete: {reason}",
  "auth.empty": "Enter a username and a password",
  "auth.network": "Could not reach the local Host",
  "panel.empty": "No data yet.",
  "section.pools": "Credit pools",
  "pool.window5h": "5 hours",
  "pool.window7d": "Weekly",
  "pool.used": "Used",
  "pool.remaining": "Remaining",
  "pool.reset": "resets {time}",
  "pool.grant": "Grant balance {balance}",
  "pool.grantExpiry": "Next grant expiry {time} ({balance} cr)",
  "pool.models": "Models",
  "pool.dedicated": "dedicated",
  "pool.default": "default",
  "pool.callable": "Callable",
  "pool.locked": "+{count} need activation",
  "pool.lockedTitle": "In the plan but this key has no permission",
  "pool.uncounted": "Not billed to credit pools: {models}",
  "shape.api": "endpoint",
  "shape.missing": "missing field",
  "section.trend": "Per-model consumption (last {hours} h)",
  "trend.model": "Model",
  "trend.credits": "Credits",
  "trend.none": "No consumption in this range.",
  "auth.selfRenew": "Token renews itself",
  "auth.needsLogin": "Sign-in required",
  "note": "Data from the SenseNova console API (pool-usage / credit-usage-trend), cached {cache}s on the Host; the console token lasts ~3h and the Host renews it silently from a refresh token."
};
